### ISSUE TITLE
use type state pattern for database entries

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-data-services#184]
most of our ORM models look like this 
```
class Entity(BaseORM):
    id: str | None = none
    [...]
```

This is because before the Entity is inserted in the database, e.g. on POST, it does not have an id. Once it is in the database, it then always has an id.

This leads to some not so nice code, having to either ignore a type error about id being None, when we know for a fact it is not, or having to check its None-ness and raise an exception in a lot of places.

We could make this much nicer by adopting a type-state style pattern, similar to what is done [here](https://gist.github.com/qexat/cfa25c740d959aa6a68bc02bf019512f) and then methods can specify if the accept `Entity[Literal["New"]]` or `Entity[Literal["Saved"]]` or just any entity. This way we don't need to deal with type errors and the api of functions clearly says what it expects.
(the `Literal["..."]` syntax might be abbreviated more with some alias, potentially, and I think there's some mypy magic needed like @overload for it to work. Alternatively we can just use polymorphism with a child class that has an id and a parent that doesn't)

Things to do this for:
- all ORMs that have an id
- `APIUser`

also remove any `# type: ignore` style comments that were added because of this.

**Comment by olevski** [comment]
Followup from #180 and #116

**Comment by Panaetius** [comment]
oh and [here's](https://boinkor.net/2024/04/some-useful-types-for-database-using-rust-web-apps/#the-idtype-trait) the rust example of exactly this (this is a common pattern in Rust)
