### ISSUE TITLE
Use single dispatch for authorization database update decorators

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#190]
See https://docs.python.org/3/library/functools.html#functools.singledispatch

This would make it so that we do not have to have so many match-case statements and have the function automatically call different code based on an argument value.

**Comment by Panaetius** [comment]
singledispatch only works with real types, not NewTypes or things like `Literal[...]` but in authz most of the matching is on concrete values and types. So singledispatch wouldn't actually make the code more readable and doesn't fit well. closing this.
