### ISSUE TITLE
Logging is broken in `background_jobs`

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-data-services#267]
The `background_jobs` containers produce no logs.

Root cause: The containers are initialized with `logging.basicConfig(level=logging.INFO)` but this is overridden by Alembic when we call `run_migrations_for_app()`.

See configuration in `alembic.ini`:
https://github.com/SwissDataScienceCenter/renku-data-services/blob/8634341630624a75e22d4ff60bc63b3a98e3dab9/components/renku_data_services/migrations/alembic.ini#L89-L92

This means after migrations are run, only `WARN` and above messages are logged.

**Comment by olevski** [comment]
Fixed in #277 by setting the level in alembic.ini to `INFO`.
