### ISSUE TITLE
Issues adding resource pool through swagger

### ISSUE THREAD

**Issue by wesjdj** [SwissDataScienceCenter/renku-data-services#32]
When trying to add a resource pool using the swagger API, `default_storage` and `default` are missing from the request body.

A quota is provided in the request body. When posted, I get this error:

```
{
  "error": {
    "code": 1422,
    "message": "A default resource pool cannot have a quota."
  }
}
```

When I remove the quota I get this error:

```
{
  "error": {
    "code": 1422,
    "message": "The quota in the resource pool is malformed."
  }
}
```

I don't understand what actually needs to be in the request body.

**Comment by olevski** [comment]
Testing this on 0.12.0 on dev.renku.ch.

The example payload now includes `default_storage` and `default`.

The payload now is as follows by default
```
{
  "quota": {
    "cpu": 50,
    "memory": 250,
    "gpu": 10
  },
  "public": true,
  "default": false,
  "classes": [
    {
      "name": "resource class 1",
      "cpu": 1.5,
      "memory": 2,
      "gpu": 0,
      "max_storage": 10,
      "default_storage": 2,
      "default": true
    },
    {
      "name": "resource class 2",
      "cpu": 4.5,
      "memory": 10,
      "gpu": 2,
      "max_storage": 10,
      "default_storage": 2,
      "default": false
    }
  ],
  "name": "resource pool name"
}
```

The default includes a quota and can be created without a problem.
