### ISSUE TITLE
only default class can be updated

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-data-services#34]
Pretty sure this isn't intended, but trying `PATCH` or `PUT` on `/resource_pools/<pool-id>/<class-id>` returns

```json
{
  "error": {
    "code": 1422,
    "message": "Only the default resource class can be updated."
  }
}
```

**Comment by olevski** [comment]
I tried this on 0.12.0 for a PUT on a default and non-default class and it worked.
