### ISSUE TITLE
investigate high memory usage

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-data-services#36]
Currently, CRC uses ~930mb of memory in all deployments.

We should investigate if this can be lowered. Maybe lowering resource requests would already help since `--fast` autoscales to what is available. 

If not, we should investigate where the memory is being used and see if there's a way to lower the footprint.

**Comment by olevski** [comment]
@Panaetius this went down when we lowered the number of workers. Now it is at around 350Mi. I checked on the renkulab.io. It has been like that for the last 30 days - I checked on Grafana.

Previously it used 6 or 8 workers and each worker runs in a separate process duplicating the memory consumption of another worker.

We addressed this in this PR: https://github.com/SwissDataScienceCenter/renku-data-services/pull/59

**Comment by olevski** [comment]
I propose we close this, what do you think?
