### ISSUE TITLE
Implement additional API input validation

### ISSUE THREAD

**Issue by sgaist** [SwissDataScienceCenter/renku-data-services#398]
Some endpoint parameters such as `server_name` don't have validation beside a type being provided.

This ticket tracks the work to provide proper validation in these case since, for example, the format of `server_name` is known so we can avoid querying the backend if the input is known to be invalid.

**Comment by olevski** [comment]
Done in #375 in a comment to resolve the comment.

https://github.com/SwissDataScienceCenter/renku-data-services/pull/375/commits/259710d8361e136d3cf6c0264bf472d6acdba607
