### ISSUE TITLE
Investigate Secret Storage (Vault)

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#50]
We need a way to store and use user's secrets in Renku. And vault is a potential solution to this problem.

**Comment by olevski** [comment]
Notes from Vault research:

Pros:
- Most likely the authorization scheme and organization of secrets can be encoded in Vault
- JWTs can be used for authentication

Cons:
- Will have to encode authorization policies for secrets in Vault with HCL and then encode authorization policies outside of Vault for everything else.
- There is a more flexible/powerful way to define policies in Vault with a language called Sentinel, but this is only available in paid/commercial versions. What if we find out the HCL policies are not flexible enough and we need Sentinel?
- What if Hashicorp changes the vault license like it did on Terraform?

Other alternatives:
- [Confidant](https://lyft.github.io/confidant/) (created by Lyft)
- [Keywhiz](https://square.github.io/keywhiz/) (created by Square)
- [Knox](https://github.com/pinterest/knox) (created by Pinterest)

**Comment by olevski** [comment]
**Notes from Knox:**

- will have to edit the Go code to setup a postgres backend
- by default, the client uses mTLS with a hardcoded signed cert given for example.com for machine authentication and had github authentication enabled for users
- for other authentication schemes we have to implement a go interface that will do the authentication we want
- limited options for authorization policies, access based on user, machine, usergroup and machine prefix (i.e. hostname of the client)
- we could potentially try to bypass the existing authorization and offload it to whatever we will use for authorization (this is not mentioned in the docs in the same way that you can have custom authentication)

**Comment by olevski** [comment]
**Notes from Confidant:**
- depends on AWS KMS and IAM for authentication
- needs DynamoDB for storing secrets

Conclusion: Not an option - not flexible enough for authentication and storage

**Comment by olevski** [comment]
**Notes from Keywhiz:**
- authentication via mTLS and LDAP
- needs MySQL for storing secrets

Conclusion: Not an option - not flexible enough for authentication and storage

**Comment by olevski** [comment]
Conclusion implement our own simple secret storage in Postgres.

**Comment by leafty** [comment]
> * What if Hashicorp changes the vault license like it did on Terraform?

This is already the case. Currently, OpenBao is incubating at the Linux Foundation to offer a FOSS fork of Vault.
See: https://www.theregister.com/2023/12/08/hashicorp_openbao_fork/
