### ISSUE TITLE
Need to support new list type for docker v2 manifests

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-data-services#525]
See `image.py` -> https://github.com/SwissDataScienceCenter/renku-data-services/blob/220a56016eb17e5e6a71e856f9d3c80a86a546f6/components/renku_data_services/notebooks/api/classes/image.py#L16.

A new response type needs to be handled: `application/vnd.docker.distribution.manifest.list.v2+json`. This should be similar to `application/vnd.oci.image.index.v1+json` where the response lists multiple images for different platforms.

**Comment by olevski** [comment]
This image `docker pull jupyter/minimal-notebook:latest` will fail the test because of exactly this reason.
