### ISSUE TITLE
Sessions: document and add more Renku environment variables.

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-data-services#528]
Currently, a session will have two Renku environment variables:
* `RENKU_BASE_URL`: the base URL of the session, e.g. `https://ci-renku-3712.dev.renku.ch/sessions/flora-thieba-dcae314cd1a4`
* `RENKU_BASE_URL_PATH`: the path component of the `RENKU_BASE_URL`, e.g. `/sessions/flora-thieba-dcae314cd1a4`

Suggested new environment variables:
* `RENKU_SESSION`: always equal to `"1"` inside a Renku session. This can be used by scripts or entrypoints.
* `RENKU_SESSION_PORT`: the port which should provide the session frontend, e.g. `8888` for JupyterLab.
* `RENKU_SESSION_IP` (less important): the IP address the frontend should listen to. Right now, most session images will listen on `0.0.0.0`, but we can allow image authors to listen only on the intended IP address
* `RENKU_WORKING_DIR`: the value of the `working_directory` setting. This should allow frontends to open the intended workspace and not just `~`.

**Comment by olevski** [comment]
One more addition here: `RENKU_MOUNT_DIR` would also be useful. The mount dir is what gets preserved during a hibernation of the session and it is usually different than the `RENKU_WORK_DIR` so it is useful to know both.
