### ISSUE TITLE
ContainerImage isn't validated in environments endpoints

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-data-services#551]
We should validate that the image name for an environment is actually a valid image identifier. Currently it accepts any character, including spaces. This then causes session launch to fail because it can't find the image, but is very difficult to spot that this happened in the input field. (so ` renku/myimage` doesn't work where `renku/myimage` works).

ideally we'd also validate this in the UI.
For reference, one of these two won't launch(due to a space in the beginning):
![image](https://github.com/user-attachments/assets/1c131379-a897-48ad-8ed7-d588dee06f92)
![image](https://github.com/user-attachments/assets/f384e1d2-a71e-4333-b0be-8c1aa5919bf7)

**Comment by leafty** [comment]
Thanks @Panaetius, for the UI side, we could use trimming before sending. Is there a validation rule for container image references?

**Comment by Panaetius** [comment]
https://docs.docker.com/reference/cli/docker/image/tag/ describes it a bit, which refers to this spec: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests which has `[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*` for the image name/path and `[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}` for the tag, if I'm reading this correctly.
