### ISSUE TITLE
Parsing request as json fails

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#58]
In some cases we expect the request to be json but it is not. I think this failure happens even if the request is empty.

This is from logs on renkulab.io

![image](https://github.com/SwissDataScienceCenter/renku-data-services/assets/16360283/da0f53d4-a4b1-4b7a-8f9e-ac58f38b24bb)

**Comment by m-alisafaee** [comment]
I could not re-produce this. Let's close it now and re-open it if it happens again.
