### ISSUE TITLE
Removing/clearing certain nullable fields on a session launcher fails

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#580]
Seen on renku 0.61.2

To replicate:
- create a session launcher
- set the mount directory to something
- try to remove it and have it be blank (this will not work)

The request succeeds but the value is left the same (i.e. the mount directory is not cleared). This is because the backend probably drops all null fields in the validation and therefore removes the mount dir field.

This is probably the same for the workdir and other session launcher fields that can be null.

**Comment by leafty** [comment]
There is no `RESET` logic with `working_directory` and `mount_directory` for session environments at the moment. I can update the logic to work like `secrets_mount_directory` on projects: sending `""` (empty string) will reset the field.
